version: '3'

services:
  temboardui-ui:
    image: dalibo/temboardui-ui:latest
    ports:
      - "8888:8888"
    links:
      - temboardui-pg

  temboardui-pg:
    image: dalibo/temboardui-pg:latest

  temboard-agent-94:
    image: dalibo/temboard-agent-94:latest
    ports:
      - 5433:5432

  temboard-agent-95:
    image: dalibo/temboard-agent-95:latest
    ports:
      - 5434:5432

  temboard-agent-96:
    image: dalibo/temboard-agent-96:latest
    ports:
      - 5435:5432
