version: '3'

volumes:
  data96:
  run96:

  data95:
  run95:

  data94:
  run94:


services:
  ui:
    image: dalibo/temboard:latest
    links:
      - repository
    environment:
      PGHOST: repository
      PGUSER: temboard
      PGPASSWORD: temboard
    ports:
      - "8888:8888"
    links:
      - repository

  repository:
    image: postgres:9.6
    environment:
      POSTGRES_USER: temboard
      POSTGRES_PASSWORD: temboard

  instance96:
    image: postgres:9.6
    ports:
      - 5433:5432
    volumes:
      - data96:/var/lib/postgresql/data
      - run96:/var/run/postgresql

  agent96:
    image: dalibo/temboard-agent
    volumes:
      - data96:/var/lib/postgresql/data
      - run96:/var/run/postgresql/
      - /usr/bin/docker:/usr/bin/docker
      - /var/run/docker.sock:/var/run/docker.sock
    links:
      - instance96:temboard-agent-96.temboard.local
      - ui
    environment:
      TEMBOARD_HOSTNAME: temboard-agent-96.temboard.local
      TEMBOARD_KEY: key_for_agent_96
      TEMBOARD_UI_URL: https://ui:8888/
    networks:
      default:
        aliases:
          - temboard-agent-96

  instance95:
    image: postgres:9.5
    ports:
      - 5434:5432
    volumes:
      - data95:/var/lib/postgresql/data
      - run95:/var/run/postgresql

  agent95:
    image: dalibo/temboard-agent
    volumes:
      - data95:/var/lib/postgresql/data
      - run95:/var/run/postgresql/
      - /usr/bin/docker:/usr/bin/docker
      - /var/run/docker.sock:/var/run/docker.sock
    links:
      - instance95:temboard-agent-95.temboard.local
      - ui
    environment:
      TEMBOARD_HOSTNAME: temboard-agent-95.temboard.local
      TEMBOARD_KEY: key_for_agent_95
      TEMBOARD_UI_URL: https://ui:8888/
    networks:
      default:
        aliases:
          - temboard-agent-95

  instance94:
    image: postgres:9.4
    ports:
      - 5435:5432
    volumes:
      - data94:/var/lib/postgresql/data
      - run94:/var/run/postgresql

  agent94:
    image: dalibo/temboard-agent
    volumes:
      - data94:/var/lib/postgresql/data
      - run94:/var/run/postgresql/
      - /usr/bin/docker:/usr/bin/docker
      - /var/run/docker.sock:/var/run/docker.sock
    links:
      - instance94:temboard-agent-94.temboard.local
      - ui
    environment:
      TEMBOARD_HOSTNAME: temboard-agent-94.temboard.local
      TEMBOARD_KEY: key_for_agent_94
      TEMBOARD_UI_URL: https://ui:8888/
    networks:
      default:
        aliases:
          - temboard-agent-94
